version: '3.4'
services:
  server-vista:
    hostname: server-vista
    container_name: server-vista
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    image: server-vista
    ports:
      - "80:8080"
    volumes:
      - ./src:/var/www
      - ./log:/var/log/nginx
    networks:
      - vista
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vista
  db-vista:
    container_name: db-vista
    build: docker/percona
    image: db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: vista
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: vista
    volumes:
      - ./db/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./.docker/percona/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    networks:
      - vista

networks:
  vista:
    driver: bridge
